services:
  postgres:
    image: postgres:16
    container_name: db-postgres
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PG_INIT_HOST_DIR:-./postgres/init}:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  analysis-job:
    build:
      context: .
      dockerfile: Dockerfile.analysis   
    container_name: analysis-job
    depends_on:
      postgres:
        condition: service_healthy
      etl-job-silver-to-gold:
        condition: service_completed_successfully  
    env_file:
      - ./.env
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
    volumes:
      - .:/app
    working_dir: /app/dataLayer/silver

  analysis-job-raw:
    build:
      context: .
      dockerfile: Dockerfile.analysis   
    container_name: analysis-job-raw
    depends_on:
      postgres:
        condition: service_healthy
      etl-job-silver-to-gold:
        condition: service_completed_successfully  
    env_file:
      - ./.env
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
    volumes:
      - .:/app
    working_dir: /app/dataLayer/raw
    
  etl-job-raw-to-silver:
    build: 
      context: .
      dockerfile: Dockerfile.silver 
    container_name: etl-job-raw-to-silver
    
    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - ./.env

    environment:
      DB_HOST: postgres
      DB_PORT: "5432"  

    volumes:
      - .:/app

    working_dir: /app/transformer
  
  etl-job-silver-to-gold:
    build: 
      context: .
      dockerfile: Dockerfile.gold 
    container_name: etl-job-silver-to-gold
    
    depends_on:
      postgres:
        condition: service_healthy
      etl-job-raw-to-silver:
        condition: service_completed_successfully

    env_file:
      - ./.env

    environment:
      DB_HOST: postgres
      DB_PORT: "5432"  

    volumes:
      - .:/app

    working_dir: /app/transformer
  


volumes:
  pgdata: